graph TD
Gouderz --a pour fils aîné--> Guiv
Gouderz --a pour descendant--> Bahram
Gouderz --a pour descendant--> Schapour
Gouderz --a pour descendant--> Rivniz
Guiv --est le gendre de--> Rustem
Guiv --a pour fils--> Bijen
Rivniz --est tué par--> Firoud
