graph TD
Keschwad --a pour fils--> Gouderz
Gouderz --a pour fils aîné--> Guiv
Gouderz --a pour fils--> Rehham
Gouderz --a pour fils--> Bahram
Gouderz --a pour descendant--> Schapour
Gouderz --a pour descendant--> Rivniz
Guiv --est le gendre de--> Rustem
Guiv --a pour fils--> Bijen
Rivniz --est tué par--> Firoud
Bahram --est tué par--> Tejaou
Afrasiab --a pour gendre--> Tejaou
