graph TD
Kaïoumors --a pour fils--> Siamek
Siamek --a pour fils--> Houscheng
Houscheng --a pour fils--> Thahmouras
Thahmouras --a pour fils--> Djemschid
Djemschid --a pour fils--> Humaïoun
Humaïoun --a pour fils-->Abtin/Atsial
Abtin/Atsial --a pour fils--> Feridoun
Thehour --a pour fille--> Ferirenk/Firanek
Ferirenk/Firanek --a pour fils--> Feridoun
Feridoun --a pour frère--> Kejanousch
Feridoun --a pour frère--> Purmajeh
Thahmasp --a pour fils--> Zew