graph TD
Kaïoumors --a pour fils--> Siamek
Siamek --a pour fils--> Houscheng
Houscheng --a pour fils--> Thahmouras
Thahmouras --a pour fils--> Djemschid
Djemschid --a pour fils--> Humaïoun
Humaïoun --a pour fils-->Abtin/Atsial
Abtin/Atsial --a pour fils--> Feridoun
Thehour --a pour fille--> Ferirenk/Firanek
Ferirenk/Firanek --a pour fils--> Feridoun
Feridoun --a pour frère--> Kejanousch
Feridoun --a pour frère--> Purmajeh
Thahmasp --a pour fils--> Zew
Ardeschir --a pour fils--> Darab
Darab --a pour fils--> Dara
Feridoun --a pour fils-->Iredj
Feridoun --a pour fils-->Tour
Feridoun --a pour fils-->Selm
Iredj --est tué par--> Tour
Kejanousch --a pour fils-->Pescheng
Iredj --a pour fille--> Y(inconnue)
Y --a pour fils--> Minoutchehr
Pescheng --a pour fils--> Minoutchehr
Tour --est tué par-->Minoutchehr
Selm --est tué par-->Minoutchehr
Minoutchehr --a pour fils--> Newder
Minoutchehr --a pour fils--> Zarasp