graph TD
Houscheng --a pour fils--> Keriman
Keriman --a pour descendant--> Neriman
Neriman --a pour fils--> Sam
Sam --a pour fils--> F(un enfant aux cheveux blanc)
Sam --abandonne à la naissance--> F(un enfant aux cheveux blanc)
F(un enfant aux cheveux blanc) --est élevé par le--> Simurgh
F(un enfant aux cheveux blanc) --est appelé par le Simurgh--> Destan
Simurgh --rend Destan à --> Sam
Destan -- est appelé par Sam --> Zal-zer
Zal-zer -- ou --> Zal/Destan
Zal/Destan --a pour fils--> Rustem/Tehemten
Roudabeh --a pour fils--> Rustem/Tehemten
Zal/Destan --a pour fils--> Zewareh
Rustem/Tehemten --a pour fils--> Faramourz
Rustem/Tehemten --a pour fils--> Sohrab
Sohrab --a été tué par--> Rustem/Tehemten
Rustem/Tehemten --a pour gendre--> Guiv
Zohak --a pour descendant--> Mihrad
Mihrad --a pour fille--> Roudabeh
Sindokht --a pour fille--> Roudabeh
Zal/Destan --a pour fils--> Scheghad
E(Une esclave) --a pour fils--> Scheghad
Zewareh --a été tué par--> R(Le Roi de Kaboul)
Rustem/Tehemten --a été tué par--> R(Le Roi de Kaboul)
Scheghad --a été tué par--> Rustem/Tehemten 
