graph TD
Neriman --a pour fils--> Sam
Sam --a pour fils--> Zal/Destan
Zal/Destan --a pour fils--> Rustem
Zal/Destan --a pour fils--> Zewareh
Rustem --a pour fils--> Faramourz
Rustem --a pour gendre--> Guiv
