graph TD
Neriman --a pour fils--> Sam
Sam --a pour fils--> Zal/Destan
Zal/Destan --a pour fils--> Rustem/Tehemten
Zal/Destan --a pour fils--> Zewareh
Rustem/Tehemten --a pour fils--> Faramourz
Rustem/Tehemten --a pour gendre--> Guiv
