graph TD
Zoroastre --est fils de--> Poroschasp
Zoroastre --a pour mère--> Dogdo
Dogdo --est fille de--> Rahémereva
Zoroastre --est né à --> Urmi
Zoroastre --est né en --> A>"550 avant J.C. (estimation)"]
Urmi --est situé dans --> Aderbedjan
Poroschasp --est fils de--> Peterasp
Peterasp  --est fils de--> Orouedasp
Orouedasp  --est fils de--> Hetchedasp
Hetchedasp  --est fils de--> Tchakhschenosch
Tchakhschenosch  --est fils de--> Peteras
Peteras  --est fils de--> Hedéresné
Hedéresné  --est fils de--> Herdaré
Herdaré  --est fils de--> Sepétaméhé
Sepétaméhé  --est fils de--> Vedest
Vedest  --est fils de--> Ezem
Ezem  --est fils de--> Resesné
Resesné  --est fils de--> Dorouantchoun
Dorouantchoun  --est fils de--> Minotcher
Minotcher  --est fils de--> Irets
Irets  --est fils de--> Feridoun
