graph TD
Feridoun --a pour fils--> Selm
Feridoun --a pour fils--> Tour
Selm --a pour descendant--> K(Kaisar du pays de Roum)
Kobad --a pour descendant--> Peschin
Peschin --a pour descendant--> Awrend
Awrend --a pour fils--> Lohrasp
Lohrasp --a pour fils--> Guschtasp
Kitaboun --choisi--> Guschtasp
Lohrasp --a pour fils--> Zerir
K(Kaisar du pays de Roum) --a pour fille --> Kitaboun
Nahib --est le premier nom de --> Kitaboun
Kitaboun --a pour frère--> Sekil
K(Kaisar du pays de Roum) --a pour fils--> Sekil 
Kitaboun --a pour fils--> Beschouten/Paschoutan
Kitaboun --a pour fils--> Isfendiar
Guschtasp --a pour fils--> Beschouten/Paschoutan
Guschtasp --a pour fils--> Isfendiar
Guschtasp --a pour fils--> Schidasp
Guschtasp --a pour fils--> Nivzar
Guschtasp --a pour fils--> A1(Ardeschir)
Guschtasp --a pour fils--> Ormuzd
Guschtasp --a pour fils--> Ferschidwerd
Guschtasp --a pour fille--> Homaï
Guschtasp --a pour fille--> Beh-Aferid
A1(Ardeschir) --tué --> B(au champs de bataille)
Ormuzd --tué --> B(au champs de bataille)
Schidasp --tué --> B(au champs de bataille)
Zerir --a pour fils--> Nestour
Zerir --tué --> B(au champs de bataille)
Isfendiar --a pour fils--> Nousch-Ader
Isfendiar --a pour fils--> Mihri-Nousch
Isfendiar --a pour fils--> Bahman
Isfendiar --a pour fils--> Ader-Afrouz
Homaï --est fiancée par Guschtasp à--> Beschouten/Paschoutan
Zoroastre --rend immortel--> Beschouten/Paschoutan
Lohrasp --tué par --> Ardjasp
Ferschidwerd --tué --> C(au champs de bataille contre Ardjasp)
Nousch-Ader --est tué --> D(au champs de bataille contre Rustem)
Mihri-Nousch --est tué --> D(au champs de bataille contre Rustem)
Isfendiar --est tué --> D(au champs de bataille contre Rustem)
Bahman --devient --> A2(Ardeschir)