graph TD
Wiseh --a pour fils--> Piran
Piran --a pour frère-->Houman
Piran --a pour fille--> Djerireh
Siawusch --a pour fils--> Khosrou
Djerireh --a pour fils--> Firoud
Siawusch --a pour fils--> Firoud
Djerireh --se tue à la mort de--> Firoud
Firoud --est tué par--> Bijen
