graph TD
Zadschem --a pour fils--> Pescheng
Pescheng --a pour fils--> Afrasiab
Pescheng --a pour fils--> Aghrirez
Afrasiab --a pour fille--> Ferenguis
Afrasiab --a pour fils--> Schideh
Afrasiab --a pour fils--> Surkeh
Afrasiab --commandite la mort de--> Ferenguis
Ferenguis --est cachée par --> Piran
Kaweh --a pour fils--> Karen
Wiseh --a pour fils--> Piran
Wiseh --a pour fils--> Kuroukhan
Wiseh --a pour fils--> Barman
Barman --est tué par--> Karen
Piran --a pour frère-->Houman
Piran --a pour fille--> Djerireh
Keïkobad --a pour fils--> Kaous
Kaous --a pour fils--> Feribourz
Kaous --a pour fils--> Siawusch
Siawusch --a pour fils--> Khosrou
Ferenguis --a pour fils--> Khosrou
Djerireh --a pour fils--> Firoud
Siawusch --a pour fils--> Firoud
Djerireh --se tue à la mort de--> Firoud
Firoud --est tué par--> Bijen
Feribourz --prend pour épouse --> Ferenguis
