graph TD
Newder --a pour fils--> Gustehem/Kustehem
Newder --a pour fils--> Thous
Guejdehem --a pour fils--> Kustehem
Thous --a pour fils--> Zerasp
Thous --a pour gendre--> Rivniz
Zerasp --est tué par--> Firoud