graph TD
Lohrasp --a pour fils--> Guschtasp
Lohrasp --a pour fils--> Zerir
Nahib --est le premier nom de --> Kitaboun
Kitaboun --choisi--> Guschtasp
Kitaboun --fille du--> K(Kaisar du pays de Roum)
Kitaboun --a pour frère--> Sekil
Sekil --fils du--> K(Kaisar du pays de Roum)
Kitaboun --a pour fils--> Beschouten/Paschoutan
Kitaboun --a pour fils--> Isfendiar
Guschtasp --a pour fils--> Beschouten
Guschtasp --a pour fils--> Isfendiar