graph TD
Lohrasp --a pour fils--> Guschtasp
Lohrasp --a pour fils--> Zerir
Nahib --est le premier nom de --> Kitaboun
Kitaboun --choisi--> Guschtasp
K(Kaisar du pays de Roum) --a pour fille --> Kitaboun
Kitaboun --a pour frère--> Sekil
K(Kaisar du pays de Roum) --a pour fils--> Sekil 
Kitaboun --a pour fils--> Beschouten/Paschoutan
Kitaboun --a pour fils--> Isfendiar
Guschtasp --a pour fils--> Beschouten/Paschoutan
Guschtasp --a pour fils--> Isfendiar
Guschtasp --a pour fils--> Schidasp
Guschtasp --a pour fils--> Nivzar
Guschtasp --a pour fils--> Ardeschir
Guschtasp --a pour fils--> Ormuzd
Guschtasp --a pour fille--> Homaï
Ardeschir --tué --> B(au champs de bataille)
Ormuzd --tué --> B(au champs de bataille)
Schidasp --tué --> B(au champs de bataille)
Zerir --a pour fils--> Nestour
Zerir --tué --> B(au champs de bataille)
Isfendiar --a pour fils--> Nousch-Ader
Isfendiar --a pour fils--> Mihri-Nousch
Homaï --est fiancée par Guschtasp à--> Beschouten/Paschoutan