graph TD
Lohrasp --a pour fils--> Guschtasp
Lohrasp --a pour fils--> Zerir
Nahib --est le premier nom de --> Kitaboun
Kitaboun --choisi--> Guschtasp
K(Kaisar du pays de Roum) --a pour fille --> Kitaboun
Kitaboun --a pour frère--> Sekil
K(Kaisar du pays de Roum) --a pour fils--> Sekil 
Kitaboun --a pour fils--> Beschouten/Paschoutan
Kitaboun --a pour fils--> Isfendiar
Guschtasp --a pour fils--> Beschouten/Paschoutan
Guschtasp --a pour fils--> Isfendiar
Guschtasp --a pour fils--> Schidasp
Guschtasp --a pour fils--> Nivzar
Zerir --a pour fils--> Nestour