graph TD
Guschtasp --a pour fils--> Isfendiar
Isfendiar --a pour fils--> Nousch-Ader
Isfendiar --a pour fils--> Mihri-Nousch
Isfendiar --a pour fils--> Bahman
Isfendiar --a pour fils--> Ader-Afrouz
Nousch-Ader --est tué --> D(au champs de bataille contre Rustem)
Mihri-Nousch --est tué --> D(au champs de bataille contre Rustem)
Isfendiar --est tué --> D(au champs de bataille contre Rustem)
Bahman --devient --> A2(Ardeschir)
A2(Ardeschir) --a pour fils--> S1(Sasan)
A2(Ardeschir) --a pour fille--> H2(Homaï/Tchehrzad)
A2(Ardeschir) --épouse sa fille--> H2(Homaï/Tchehrzad)
A2(Ardeschir) --met enceinte--> H2(Homaï/Tchehrzad)
A2(Ardeschir) --meurt de--> maladie
S1(Sasan) --s'enfuit incognito au--> Nischapour
S1(Sasan) --épouse incognito une fille de--> Nischapour
S1(Sasan) --a pour fils--> S2(Sasan)
S2(Sasan) --devient pâtre du roi de--> Nischapour
H2(Homaï/Tchehrzad) --accouche en secret du --> S3(fils d'Ardeschir)
S3(fils d'Ardeschir) --est abandonné sur --> Euphrate
